### ISSUE TITLE
Requesting /follow gives NoMethodError: undefined method `slice!' for nil:NilClass

### ISSUE THREAD

**Issue by donv** [binford2k/showoff#246]
Hi!

When I run https://github.com/donv/ruby_for_java_developers (either locally or on heroku) and request `/follow`, I get the following error:

```
2015-04-09T12:20:37.701476+00:00 heroku[router]: at=info method=GET path="/follow" host=ruby-for-java.herokuapp.com request_id=31dcd98a-9c73-4d13-9bb5-ae71e66cfab1 fwd="139.112.1.135" dyno=web.1 connect=1ms service=7ms status=500 bytes=153
2015-04-09T12:20:37.699968+00:00 app[web.1]:  Invalid object follow requested.
2015-04-09T12:20:37.700084+00:00 app[web.1]: 2015-04-09 12:20:37 +0000: Rack app error: #<NoMethodError: undefined method `slice!' for nil:NilClass>
2015-04-09T12:20:37.700162+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/showoff-0.9.10.8/lib/showoff.rb:1274:in `block in <class:ShowOff>'
2015-04-09T12:20:37.700165+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
2015-04-09T12:20:37.700166+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
2015-04-09T12:20:37.700168+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `[]'
2015-04-09T12:20:37.700170+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
2015-04-09T12:20:37.700171+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
2015-04-09T12:20:37.700173+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
2015-04-09T12:20:37.700175+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1134:in `block in error_block!'
2015-04-09T12:20:37.700183+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1131:in `reverse_each'
2015-04-09T12:20:37.700194+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1131:in `error_block!'
2015-04-09T12:20:37.700195+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1120:in `handle_exception!'
2015-04-09T12:20:37.700197+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1087:in `block in dispatch!'
2015-04-09T12:20:37.700198+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
2015-04-09T12:20:37.700200+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
2015-04-09T12:20:37.700202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
2015-04-09T12:20:37.700203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1087:in `rescue in dispatch!'
2015-04-09T12:20:37.700205+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1094:in `dispatch!'
2015-04-09T12:20:37.700207+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
2015-04-09T12:20:37.700208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
2015-04-09T12:20:37.700210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
2015-04-09T12:20:37.700211+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
2015-04-09T12:20:37.700213+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
2015-04-09T12:20:37.700216+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
2015-04-09T12:20:37.700217+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2015-04-09T12:20:37.700219+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2015-04-09T12:20:37.700220+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2015-04-09T12:20:37.700222+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-04-09T12:20:37.700223+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2015-04-09T12:20:37.700224+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2015-04-09T12:20:37.700226+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
2015-04-09T12:20:37.700228+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/rack_patch.rb:13:in `call'
2015-04-09T12:20:37.700229+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
2015-04-09T12:20:37.700231+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
2015-04-09T12:20:37.700232+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
2015-04-09T12:20:37.700234+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
2015-04-09T12:20:37.700235+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
2015-04-09T12:20:37.700237+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
2015-04-09T12:20:37.700238+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/configuration.rb:82:in `call'
2015-04-09T12:20:37.700240+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
2015-04-09T12:20:37.700241+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
2015-04-09T12:20:37.700242+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
2015-04-09T12:20:37.700244+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
2015-04-09T12:20:37.700245+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by donv** [comment]
Anyone else getting this?

**Comment by donv** [comment]
Fixing the immediate error of method_missing gives that the "/follow" path is unknown => 404

Anyone else seeing this?

**Comment by binford2k** [comment]
I strongly suspect this was due to javascript cached in the client browser, since that path was deprecated long long ago. Nevertheless, a 404 shouldn't have stack traced.
